
version: '2'
services:
  nginx:
    image: "nginx"
    container_name: nginx
    volumes:
     - ./conf/nginx-fcgi-sample.conf:/etc/nginx/nginx.conf
    ports:
     - "127.0.0.1:8010:80"
    networks:
     - qgis-server-net
    restart: always
    depends_on:
     - qgis-server

  qgis-server:
    image: "qgis/qgis-server:stable"
    container_name: qgis-server
    ports:
     - "5555:5555"
    environment:
      SKIP_NGINX: "true"
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
    networks:
     - qgis-server-net
    volumes:
     - ./test/data:/io/data:ro
     - ./plugins:/io/plugins
     - ./fonts:/usr/share/fonts
     - ./svg:/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg
    restart: always

networks:
  qgis-server-net:

